#ifndef JELLYVR_VERSION_H
#define JELLYVR_VERSION_H

#define PROJECT_VERSION_MAJOR 
#define PROJECT_VERSION_MINOR 
#define PROJECT_VERSION_PATCH 
#define PROJECT_VERSION ""
#define FULL_VERSION ""

#endif
