#ifndef JELLYVR_VERSION_H
#define JELLYVR_VERSION_H

#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 15
#define PROJECT_VERSION "0.0.15"
#define FULL_VERSION "0.0.15+c85e467"

#endif
